(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['products'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<div class=\"product product_horizontal\">                                \n            <span class=\"product_code\">Код: "
    + alias4(((helper = (helper = helpers.code || (depth0 != null ? depth0.code : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"code","hash":{},"data":data}) : helper)))
    + "</span>\n            <div class=\"product_status_tooltip_container\">\n                <span class=\"product_status\">Наличие</span>\n            </div>                                \n            <div class=\"product_photo\">\n                <a href=\"#\" class=\"url--link product__link\">\n                    <img src="
    + alias4(((helper = (helper = helpers.img_dimensions || (depth0 != null ? depth0.img_dimensions : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"img_dimensions","hash":{},"data":data}) : helper)))
    + ">\n                </a>                                    \n            </div>\n            <div class=\"product_description\">\n                <a href=\"#\" class=\"product__link\">"
    + alias4(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data}) : helper)))
    + "</a>\n            </div>\n            <div class=\"product_tags hidden-sm\">\n                <p>Могут понадобиться:</p>\n<!--\n                <a href=\"#\" class=\"url--link\">подложка,</a>\n                <a href=\"#\" class=\"url--link\">плинтус натуральный,</a>\n                <a href=\"#\" class=\"url--link\">рулетка,</a>\n                <a href=\"#\" class=\"url--link\">набор для укладки ламината,</a>\n                <a href=\"#\" class=\"url--link\">ножовка по ламинату,</a>\n                <a href=\"#\" class=\"url--link\">гель для стыков ламината Clic Protect.</a>\n-->\n                "
    + ((stack1 = ((helper = (helper = helpers.links || (depth0 != null ? depth0.links : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"links","hash":{},"data":data}) : helper))) != null ? stack1 : "")
    + "\n                \n            </div>\n            <div class=\"product_units\">\n                <div class=\"unit--wrapper\">\n                    <div class=\"unit--select unit--active for-unit\" onclick=\"reg_price(this)\">\n                        <p class=\"ng-binding\">За м. кв.</p>\n                    </div>\n                    <div class=\"unit--select for-pack\" onclick=\"bulk_price(this)\">\n                        <p class=\"ng-binding\">За упаковку</p>\n                    </div>\n                </div>\n            </div>\n            <p class=\"product_price_club_card\">\n                <span class=\"product_price_club_card_text\">По карте<br>клуба</span>\n                <span class=\"goldPrice\">"
    + alias4(((helper = (helper = helpers.goldPrice || (depth0 != null ? depth0.goldPrice : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"goldPrice","hash":{},"data":data}) : helper)))
    + "</span>\n                <span class=\"rouble__i black__i\">\n                    <svg version=\"1.0\" id=\"rouble__b\" xmlns=\"http://www.w3.org/2000/svg\" x=\"0\" y=\"0\" width=\"30px\" height=\"22px\" viewBox=\"0 0 50 50\" enable-background=\"new 0 0 50 50\" xml:space=\"preserve\">\n                       <use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#rouble_black\"></use>\n                    </svg>\n                 </span>\n            </p>\n            <p class=\"product_price_default\">\n                <span class=\"retailPrice\">"
    + alias4(((helper = (helper = helpers.retailPrice || (depth0 != null ? depth0.retailPrice : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"retailPrice","hash":{},"data":data}) : helper)))
    + "</span>\n                <span class=\"rouble__i black__i\">\n                    <svg version=\"1.0\" id=\"rouble__g\" xmlns=\"http://www.w3.org/2000/svg\" x=\"0\" y=\"0\" width=\"30px\" height=\"22px\" viewBox=\"0 0 50 50\" enable-background=\"new 0 0 50 50\" xml:space=\"preserve\">\n                       <use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#rouble_gray\"></use>\n                    </svg>\n                 </span>\n            </p>\n            <div class=\"product_price_points\">\n                <p class=\"ng-binding\">Можно купить за 231,75 балла</p>\n            </div>\n            <div class=\"list--unit-padd\"></div>\n            <div class=\"list--unit-desc\">\n                <div class=\"unit--info\">\n                    <div class=\"unit--desc-i\"></div>\n                    <div class=\"unit--desc-t\">\n                        <p>\n                            <span class=\"ng-binding\">Продается упаковками:</span>\n                            <span class=\"unit--infoInn\">"
    + alias4(((helper = (helper = helpers.unitRatio || (depth0 != null ? depth0.unitRatio : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"unitRatio","hash":{},"data":data}) : helper)))
    + " "
    + alias4(((helper = (helper = helpers.unit || (depth0 != null ? depth0.unit : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"unit","hash":{},"data":data}) : helper)))
    + " = "
    + alias4(((helper = (helper = helpers.unitRatioAlt || (depth0 != null ? depth0.unitRatioAlt : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"unitRatioAlt","hash":{},"data":data}) : helper)))
    + " "
    + alias4(((helper = (helper = helpers.unitAlt || (depth0 != null ? depth0.unitAlt : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"unitAlt","hash":{},"data":data}) : helper)))
    + " </span>\n                        </p>\n                    </div>\n                </div>\n            </div>\n            <div class=\"product__wrapper\">\n                <div class=\"product_count_wrapper\">\n                    <div class=\"stepper\">\n                        <input class=\"product__count stepper-input\" type=\"text\" value=\"1\">\n                        <span class=\"stepper-arrow up\"   onclick=\"countUp(this)\" ></span>\n                        <span class=\"stepper-arrow down\" onclick=\"countDown(this)\" ></span>                                            \n                    </div>\n                </div>\n                <span class=\"btn btn_cart\" data-url=\"/cart/\" data-product-id="
    + alias4(((helper = (helper = helpers.product_id || (depth0 != null ? depth0.product_id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"product_id","hash":{},"data":data}) : helper)))
    + ">\n                    <svg class=\"ic ic_cart\">\n                       <use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#cart\"></use>\n                    </svg>\n                    <span class=\"ng-binding\">В корзину</span>\n                </span>\n            </div>\n        </div>  ";
},"useData":true});
})();